apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1 #name
spec:
  accessModes:
    - ReadWriteOnce
    #there are other modes like ReadOnlyMany, ReadWriteMany
  capacity:
    storage: 1Gi #storage for the PV
    
  #This PV will be created using Public cloud storage solutions
  awsElasticBlockStore:
    volumeID: <volume-id>
    fsType: ext4