apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1 #name
spec:
  accessModes:
    - ReadWriteOnce
    #there are other modes like ReadOnlyMany, ReadWriteMany
  capacity:
    storage: 1Gi #storage for the PV
  hostPath:
    path: /tmp/data #local path of the device where it will be created
    #never use it for production 