apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-administrator #role name
#rules allowed for this role  
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: [list,"get","create"]
