apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer #role name
#rules allowed for this role  
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: [list,"get","create"]

  - apiGroups: [""]
    resources: ["CongigMap"]
    verbs: ["create"]