apiVersion: rbac.authorization.k8s.io/v1 #here rbac.authorization.k8s.io is the api group
kind: RoleBinding
metadata:
   name: devuser-binding
subjects:
  - kind: User
    name: dev-user #user-name
    apiGroup: rbac.authorization.k8s.io

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer #Role name