#this is the green deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green
  labels:
    app: myapp
    type: frontend
spec:
  #the deployment matches the selector to track number of pods
  selector:
    matchLabels:
      version: v2 #new pod version tag
  #teplate for the pods within the deployment
  template:
    metadata:
      name: myapp-pod
      labels: 
        version: v2 #new pod version tag
      spec:
        containers:
        - name: app-container
          image: myapp-image:2.0 #new version
  replicas: 5 #5 pods to be created within the deployment
  
        
    