#this is the canary deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-canary
  labels:
    app: myapp
    type: front-end
spec:
  #the deployment matches the selector to track number of pods
  selector:
    matchLabels:
      app: front-end
  #teplate for the pods within the deployment
  template:
    metadata:
      name: myapp-pod
      labels: 
        version: v2
        app: front-end #common selector for primary and canary deployment
      spec:
        containers:
        - name: app-container
          image: myapp-image:2.0 #old version
  replicas: 1 #1 pods to be created within the deployment
  
        
    