apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reporting-cron-job #cron_job_name
spec:
  schedule: "*/1 * * * *" #the  time when the job is supposed to be run
  jobTemplate:
    spec:
      template:
        completions: 3
        parallelism: 3
        template: 
          spec:
            containers:
              - name: reporting-tool
                image: reporting-tool 
            restartPolicy: Never #we don't want the pods to restart. 