apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job #jobname
spec:
  completions: 3 #creates 3 pods to complete the command
  template:
    spec:
    #container info
      containers:
        - name: math-add
          image: ubuntu
          command: ['expr','3','+','2'] #tasks to do for the container prior to exit
      restartPolicy: Never #we don't want the pods to restart  once it fails