#PVCs are  used to claim Persistent volume of our choice
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce #it can be different as well
  storageClassName: google-storage #adding storage class name to use that instead of pv-def.yaml file
  resources:
    requests:
      storage: 500Mi #500 MB
      
