apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:  
  containers:
    - name: ubuntu
      image: ubuntu
      ports:
        - containerPort: 8080

      #using HTTP test for web app
      readinessProbe:
        httpGet:
          path: /api/ready
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 8
      
      