apiVersion: v1
kind: Pod
metadata:
  name: demo_app
  labels:
    name: demo_label
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: shared-data
    - name: sidecar-container
      image: fluent/fluentd
      volumeMounts:
        - mountPath: /pod-data
          name: shared-data

