apiVersion: v1
kind: Pod
metadata:
  name: demo_app
  labels:
    name: demo_label
spec:
  containers:
    - name: name_of_container
      image: real_image_name
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "1Gi"
          cpu: "1"
        limits:
          memory: "2Gi"
          cpu: "2"
  nodeSelector:
    size: Large #label selected for nodes